version: '3.8'

services:
  flask:
    image: hugomayo7/flask-app:latest
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:5000 || exit 1" ]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 2s
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    command: [ "sh", "-c", "sleep 10 && nginx -g 'daemon off;'" ]
    deploy:
      replicas: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  postgres-data: