name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de construction
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t hugomayo7/flask-app:latest ./flask-app

  # Job de déploiement avec Docker Compose
  deploy_docker_compose:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

  # Job de déploiement sur Docker Swarm
  deploy_docker_swarm:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Initialize Docker Swarm
        run: |
          docker swarm init || true

      - name: Create secrets for PostgreSQL
        run: |
          echo ${{ secrets.POSTGRES_PASSWORD }} | docker secret create pg_password -
          echo ${{ secrets.POSTGRES_USER }} | docker secret create pg_user -
          echo ${{ secrets.POSTGRES_DB }} | docker secret create pg_db -

      - name: Deploy stack in Docker Swarm
        run: |
          docker stack deploy -c docker-swarm.yml app_stack

      - name: Verify deployment
        run: |
          docker service ls
